# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  proton-ge = {
    pname = "proton-ge";
    version = "GE-Proton8-3";
    src = fetchurl {
      url = "https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton8-3/GE-Proton8-3.tar.gz";
      sha256 = "sha256-JYGwb0LhIs6B2/OHiU+mJ/dAAS+Dg+MrVksAsn6IS9g=";
    };
  };
  warcraftlogs = {
    pname = "warcraftlogs";
    version = "6.0.2";
    src = fetchurl {
      url = "https://github.com/RPGLogs/Uploaders-warcraftlogs/releases/download/v6.0.2/Warcraft-Logs-Uploader-6.0.2.AppImage";
      sha256 = "sha256-b1Lt8ssL+Isd/Twv6ef3AK4/BkxWA/TtleameONo/2Q=";
    };
  };
}
