#!/bin/sh

NAME=$1
if [ -z $1 ]; then
	exit 0
fi

bw list items --search $NAME |\
	jq 'reduce .[] as $item (
			""; 
			. + "=====" + $item.name + "====\n    " 
			  + $item.login.username + "\n    " 
			  + $item.login.password + "\n\n")' -r |\
	head -n -2
