name: "Build"
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: traxys
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - shell: bash -eo pipefail {0}
        run: >
          nix flake show --json |
          jq -r '.packages."x86_64-linux" | keys | .[]' | 
          NIXPKGS_ALLOW_UNFREE=1 xargs -I'{}' bash -c "echo '::group::{}'; nix build --impure '.#{}'; echo '::endgroup::'"
      - run: nix build .#checks.x86_64-linux.launch
