name: "Build"
on:
  push:
  workflow_dispatch:

jobs:
  load_packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: traxys
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - id: load-packages
        run: echo "::set-output name=matrix::$(nix flake show --json | jq -c '.packages."x86_64-linux" | keys')"

    outputs:
      matrix: ${{ steps.load-packages.outputs.matrix }}

  build:
    runs-on: ubuntu-latest
    needs: load_packages
    strategy:
      matrix:
        package: ${{ fromJson(needs.load_packages.outputs.matrix) }}
    steps:
      - run: NIXPKGS_ALLOW_UNFREE=1 nix build --impure '.#${{ matrix.package }}'
      - run: nix build .#checks.x86_64-linux.launch
