name: "Build"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * SUN' # runs weekly on Sunday at 12:00

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: traxys
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: >
          nix flake show --json |
          jq -r '.packages."x86_64-linux" | keys | .[]' | 
          NIXPKGS_ALLOW_UNFREE=1 xargs -I'{}' nix build --impure '.#{}'
