name: automerge
on:
  pull_request:
    types:
      - opened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 60
          timeoutSeconds: 1200
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          MERGE_METHOD: rebase
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
