name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          pr-title: "Update flake.lock"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge
          number: ${{ steps.update.outputs.pull-request-number }}
      - name: Update nvim-treesitter
        run: |
          git checkout update_flake_lock_action
          nix run .\#update-nvim-treesitter -- neovim/nvim-treesitter
          git add neovim/nvim-treesitter
          git commit -m "neovim: Update nvim-treesitter parsers"
          git push
